services:
    postgres:
        image: postgres:16.3-alpine3.20
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: webapp.dev
            POSTGRES_HOST_AUTH_METHOD: trust
